# Generated by Django 5.2 on 2025-06-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correctedcity',
            fields=[
                ('correctedcity_id', models.AutoField(primary_key=True, serialize=False)),
                ('correctedcity_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='rawdatacity',
            fields=[
                ('rawcity_id', models.AutoField(primary_key=True, serialize=False)),
                ('rawcity_name', models.TextField()),
            ],
        ),
    ]
