# Generated by Django 5.2 on 2025-06-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctedcity',
            name='correctedcity_id',
        ),
        migrations.RemoveField(
            model_name='rawdatacity',
            name='rawcity_id',
        ),
        migrations.AddField(
            model_name='correctedcity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='rawdatacity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='correctedcity',
            name='correctedcity_name',
            field=models.CharField(max_length=35),
        ),
    ]
