# Generated by Django 5.2 on 2025-06-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_correctedcity_correctedcity_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='correctedcity',
            new_name='ciudades_norm',
        ),
    ]
