# Generated by Django 5.2 on 2025-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_correctedcity_ciudades_norm'),
    ]

    operations = [
        migrations.CreateModel(
            name='fnac_famosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_fnac', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fnac_famosos_norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnac_name', models.TextField()),
                ('fnac_date', models.TextField()),
                ('fnac_age', models.IntegerField()),
                ('fnac_birthday', models.BooleanField()),
            ],
        ),
    ]
