# Generated by Django 5.2 on 2025-06-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fnac_famosos_fnac_famosos_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnac_famosos_norm',
            name='fnac_age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fnac_famosos_norm',
            name='fnac_birthday',
            field=models.TextField(),
        ),
    ]
