# Generated by Django 5.2 on 2025-06-18 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fnac_famosos_norm_fnac_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Georeference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=20)),
                ('city_state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
        ),
    ]
