# Generated by Django 5.2 on 2025-06-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_place_georeference_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnac_famosos_norm',
            name='fnac_birthday',
        ),
    ]
